/**
 * Curated list of known disposable and temporary email domains.
 * Blocks throwaway accounts while protecting standard public providers
 * (gmail, outlook, hotmail, yahoo, icloud, proton, zoho) and custom business domains.
 */

export const DISPOSABLE_EMAIL_DOMAINS = new Set([
  '0-mail.com',
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  '10minutemails.com',
  '20minutemail.com',
  '20mail.it',
  '33mail.com',
  'anonbox.net',
  'anonymbox.com',
  'antichef.com',
  'armyspy.com',
  'binkmail.com',
  'bobmail.info',
  'burnthespam.com',
  'cachedot.net',
  'chacuo.net',
  'crazymailing.com',
  'cuvox.de',
  'dayrep.com',
  'deadaddress.com',
  'dispostable.com',
  'discard.email',
  'discardmail.com',
  'discardmail.de',
  'disposablemail.com',
  'drdrb.net',
  'dropmail.me',
  'emailfake.com',
  'emailondeck.com',
  'emailtemporanea.net',
  'emailtemporario.com.br',
  'emkei.cz',
  'fakemailgenerator.com',
  'fleckens.hu',
  'getairmail.com',
  'getnada.com',
  'grr.la',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'gustr.com',
  'harakirimail.com',
  'incognitomail.org',
  'inboxbear.com',
  'inboxkitten.com',
  'jetable.org',
  'jourrapide.com',
  'kasmail.com',
  'klzlk.com',
  'linshiyouxiang.net',
  'maildrop.cc',
  'mailcatch.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator2.com',
  'mailnull.com',
  'mailsac.com',
  'mailtemp.top',
  'meltmail.com',
  'mohmal.com',
  'mytemp.email',
  'nada.ltd',
  'nada.name',
  'nervtemp.com',
  'netcourrier.com',
  'nospam.ze.tc',
  'nowmymail.com',
  'oneoffmail.com',
  'owlymail.com',
  'proxymail.eu',
  'rcpt.at',
  'rhyta.com',
  'safetymail.info',
  'sharklasers.com',
  'shortmail.com',
  'spambog.com',
  'spambox.us',
  'spamcannibal.org',
  'spamday.com',
  'spamfree24.org',
  'spamgourmet.com',
  'spamhole.com',
  'spaminator.de',
  'spaml.com',
  'spamspot.com',
  'superrito.com',
  'teleworm.us',
  'temp-mail.org',
  'temp-mail.ru',
  'tempail.com',
  'tempm.com',
  'tempmail.address',
  'tempmail.com',
  'tempmail.de',
  'tempmail.net',
  'tempmailaddress.com',
  'tempmailgen.com',
  'throwawaymail.com',
  'trash-mail.at',
  'trash-mail.com',
  'trashmail.com',
  'trashmail.de',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'zoemail.org',
]);

/**
 * Checks whether an email address uses a disposable/temporary email domain.
 */
export function isDisposableEmail(email: string): boolean {
  if (!email || !email.includes('@')) return false;
  const parts = email.trim().toLowerCase().split('@');
  if (parts.length !== 2) return false;
  const domain = parts[1];
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}
